version: '3.5'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 8091:8080
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password