export enum CollectorsMap {
    AssetCollector = 'Yiisoft\\Assets\\Debug\\AssetCollector',
    LogCollector = 'Yiisoft\\Yii\\Debug\\Collector\\LogCollector',
    EventCollector = 'Yiisoft\\Yii\\Debug\\Collector\\EventCollector',
    ExceptionCollector = 'Yiisoft\\Yii\\Debug\\Collector\\ExceptionCollector',
    ServiceCollector = 'Yiisoft\\Yii\\Debug\\Collector\\ServiceCollector',
    ValidatorCollector = 'Yiisoft\\Yii\\Debug\\Collector\\ValidatorCollector',
    DatabaseCollector = 'Yiisoft\\Yii\\Debug\\Collector\\Database\\DatabaseCollector',
    QueueCollector = 'Yiisoft\\Yii\\Debug\\Collector\\Queue\\QueueCollector',
    HttpClientCollector = 'Yiisoft\\Yii\\Debug\\Collector\\HttpClientCollector',
    FilesystemStreamCollector = 'Yiisoft\\Yii\\Debug\\Collector\\Stream\\FilesystemStreamCollector',
    HttpStreamCollector = 'Yiisoft\\Yii\\Debug\\Collector\\Stream\\HttpStreamCollector',
    ConsoleAppInfoCollector = 'Yiisoft\\Yii\\Debug\\Collector\\Console\\ConsoleAppInfoCollector',
    CommandCollector = 'Yiisoft\\Yii\\Debug\\Collector\\Console\\CommandCollector',
    MiddlewareCollector = 'Yiisoft\\Yii\\Debug\\Collector\\Web\\MiddlewareCollector',
}
