export enum CollectorsMap {
    AssetCollector = 'Yiisoft\\Yii\\Debug\\Collector\\AssetCollector',
    LogCollector = 'Yiisoft\\Yii\\Debug\\Collector\\LogCollector',
    EventCollector = 'Yiisoft\\Yii\\Debug\\Collector\\EventCollector',
    ExceptionCollector = 'Yiisoft\\Yii\\Debug\\Collector\\ExceptionCollector',
    ServiceCollector = 'Yiisoft\\Yii\\Debug\\Collector\\ServiceCollector',
    ValidatorCollector = 'Yiisoft\\Yii\\Debug\\Collector\\ValidatorCollector',
    DatabaseCollector = 'Yiisoft\\Yii\\Debug\\Collector\\Database\\DatabaseCollector',
    QueueCollector = 'Yiisoft\\Yii\\Debug\\Collector\\QueueCollector',
    HttpClientCollector = 'Yiisoft\\Yii\\Debug\\Collector\\HttpClientCollector',
    FilesystemStreamCollector = 'Yiisoft\\Yii\\Debug\\Collector\\FilesystemStreamCollector',
    HttpStreamCollector = 'Yiisoft\\Yii\\Debug\\Collector\\HttpStreamCollector',
    ConsoleAppInfoCollector = 'Yiisoft\\Yii\\Debug\\Collector\\ConsoleAppInfoCollector',
    CommandCollector = 'Yiisoft\\Yii\\Debug\\Collector\\CommandCollector',
    MiddlewareCollector = 'Yiisoft\\Yii\\Debug\\Collector\\MiddlewareCollector',
}
